name: Safe Settings Sync

on:
  push:
    branches:
      - main
    paths:
      - ".github/settings.yml"
      - ".github/deployment-settings.yml"
      - ".github/repos/**"
      - ".github/suborgs/**"
  schedule:
    - cron: "17 */6 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: github/safe-settings
          ref: "2.1.19"
          path: .safe-settings

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install safe-settings dependencies
        working-directory: .safe-settings
        run: npm install

      - name: Run full sync
        working-directory: .safe-settings
        env:
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GH_ORG: ${{ vars.GH_ORG }}
          ADMIN_REPO: account-administration
          CONFIG_PATH: .github
          DEPLOYMENT_CONFIG_FILE: ${{ github.workspace }}/.github/deployment-settings.yml
        run: npm run full-sync
